# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae126bcca1230b651bb69ef3dd35941eb528a588a029a2cb7219228d4311fe7743647502e32a38b8e549ddb342d83bac2074952b27b8ae5e05f36cfef14fa25d

test:
  secret_key_base: c7582e20d6c84cbbb5035604ce6ab1fb4c6057b7f5ac7073586562c106cee0d61dc62c2ac6cfb60d1aa7fee791754b207d6eacbdc63694492861af08f74e352a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
